-- Copyright 2004-2025 H2 Group. Multiple-Licensed under the MPL 2.0,
-- and the EPL 1.0 (https://h2database.com/html/license.html).
-- Initial Developer: H2 Group
--

CREATE TABLE TEST(ID INT, NAME VARCHAR(255));
> ok

CREATE UNIQUE INDEX IDX_NAME ON TEST(NAME);
> ok

SELECT IS_VISIBLE FROM INFORMATION_SCHEMA.INDEXES WHERE INDEX_NAME = 'IDX_NAME';
> IS_VISIBLE
> ----------
> TRUE
> rows: 1

ALTER INDEX IDX_NAME INVISIBLE;
> ok

SELECT IS_VISIBLE FROM INFORMATION_SCHEMA.INDEXES WHERE INDEX_NAME = 'IDX_NAME';
> IS_VISIBLE
> ----------
> FALSE
> rows: 1

ALTER INDEX IDX_NAME VISIBLE;
> ok

SELECT IS_VISIBLE FROM INFORMATION_SCHEMA.INDEXES WHERE INDEX_NAME = 'IDX_NAME';
> IS_VISIBLE
> ----------
> TRUE
> rows: 1

-- Test constraint guard
ALTER TABLE TEST ADD CONSTRAINT U_NAME UNIQUE(NAME);
> ok

ALTER INDEX IDX_NAME INVISIBLE;
> exception FEATURE_NOT_SUPPORTED_1

DROP TABLE TEST;
> ok
