-- Copyright 2004-2025 H2 Group. Multiple-Licensed under the MPL 2.0,
-- and the EPL 1.0 (https://h2database.com/html/license.html).
-- Initial Developer: H2 Group
--

CREATE TABLE TEST(G GEOMETRY);
> ok

CREATE UNIQUE SPATIAL INDEX IDX ON TEST(G);
> exception SYNTAX_ERROR_2

CREATE HASH SPATIAL INDEX IDX ON TEST(G);
> exception SYNTAX_ERROR_2

CREATE UNIQUE HASH SPATIAL INDEX IDX ON TEST(G);
> exception SYNTAX_ERROR_2

DROP TABLE TEST;
> ok

CREATE TABLE TEST(A INT, B INT, C INT);
> ok

CREATE INDEX TEST_IDX ON TEST(C) INCLUDE(B);
> exception SYNTAX_ERROR_1

CREATE UNIQUE INDEX TEST_IDX ON TEST(C) INCLUDE(B);
> ok

DROP INDEX TEST_IDX;
> ok

CREATE UNIQUE INDEX TEST_IDX_1 ON TEST(A, B, C);
> ok

CREATE UNIQUE NULLS DISTINCT INDEX TEST_IDX_2 ON TEST(A, B, C);
> ok

CREATE UNIQUE NULLS ALL DISTINCT INDEX TEST_IDX_3 ON TEST(A, B, C);
> ok

CREATE UNIQUE NULLS NOT DISTINCT INDEX TEST_IDX_4 ON TEST(A, B, C);
> ok

CREATE UNIQUE NULLS ALL DISTINCT INDEX TEST_IDX_5 ON TEST(C);
> ok

SELECT INDEX_NAME, NULLS_DISTINCT FROM INFORMATION_SCHEMA.INDEXES WHERE TABLE_NAME = 'TEST';
> INDEX_NAME NULLS_DISTINCT
> ---------- --------------
> TEST_IDX_1 YES
> TEST_IDX_2 YES
> TEST_IDX_3 ALL
> TEST_IDX_4 NO
> TEST_IDX_5 YES
> rows: 5

INSERT INTO TEST VALUES (NULL, NULL, NULL), (1, NULL, NULL), (1, 2, NULL), (1, 2, 3);
> update count: 4

INSERT INTO TEST VALUES (NULL, NULL, NULL);
> exception DUPLICATE_KEY_1

DROP INDEX TEST_IDX_4;
> ok

INSERT INTO TEST VALUES (NULL, NULL, NULL);
> update count: 1

INSERT INTO TEST VALUES (1, NULL, NULL);
> exception DUPLICATE_KEY_1

DROP INDEX TEST_IDX_3;
> ok

INSERT INTO TEST VALUES (1, NULL, NULL);
> update count: 1

DROP TABLE TEST;
> ok

-- SQL Server compatibility: NONCLUSTERED/CLUSTERED keywords and WHERE col IS NOT NULL

SET MODE MSSQLServer;
> ok

CREATE TABLE TEST(ID INT, NAME VARCHAR(100));
> ok

-- NONCLUSTERED keyword should be parsed and ignored
CREATE UNIQUE NONCLUSTERED INDEX IDX1 ON TEST(ID);
> ok

-- CLUSTERED keyword should be parsed and ignored
CREATE UNIQUE CLUSTERED INDEX IDX2 ON TEST(NAME);
> ok

-- WHERE col IS NOT NULL on single-column unique index converts to NULLS DISTINCT
CREATE UNIQUE NONCLUSTERED INDEX IDX3 ON TEST(ID) WHERE ID IS NOT NULL;
> ok

SELECT INDEX_NAME, NULLS_DISTINCT FROM INFORMATION_SCHEMA.INDEXES WHERE TABLE_NAME = 'TEST' ORDER BY INDEX_NAME;
> INDEX_NAME NULLS_DISTINCT
> ---------- --------------
> IDX1       NO
> IDX2       NO
> IDX3       YES
> rows (ordered): 3

DROP INDEX IDX1;
> ok

-- Test that NULLS DISTINCT behavior works: multiple NULLs allowed
INSERT INTO TEST VALUES (1, 'a'), (2, 'b'), (NULL, 'c'), (NULL, 'd');
> update count: 4

-- Duplicate non-null value should fail
INSERT INTO TEST VALUES (1, 'e');
> exception DUPLICATE_KEY_1

-- WHERE column must match index column
CREATE UNIQUE INDEX IDX_BAD ON TEST(ID) WHERE NAME IS NOT NULL;
> exception SYNTAX_ERROR_2

-- WHERE col IS NULL is not supported
CREATE UNIQUE INDEX IDX_BAD2 ON TEST(ID) WHERE ID IS NULL;
> exception SYNTAX_ERROR_2

DROP TABLE TEST;
> ok

SET MODE Regular;
> ok
