package org.h2.test.db;

import org.h2.test.TestBase;

import java.sql.*;
import org.h2.test.TestBase;

public class TestBug4308 extends TestBase {

    @Override
    public void test() throws Exception {
        // two-connection repro: should pass
        test4308_reproTwoConnections();

        // toggles (optional, but nice):
        test4308_reproSingleConnectionPasses();
    }

    private void test4308_reproTwoConnections() throws Exception {
        String url = "jdbc:h2:mem:test_regression;DB_CLOSE_DELAY=-1";

        String ddl =
                "CREATE TABLE parent_table (" +
                        "  child_cd VARCHAR(31) NOT NULL CHECK (child_cd IN ('A','B')), " +
                        "  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "  name VARCHAR(255), " +
                        "  a_column VARCHAR(255), " +
                        "  b_column VARCHAR(255)" +
                        ")";

        String insertSql =
                "INSERT INTO parent_table (name, a_column, child_cd, id) " +
                        "VALUES (?, ?, 'A', DEFAULT)";

        // conn1
        try (Connection c1 = DriverManager.getConnection(url);
             Statement st = c1.createStatement()) {
            st.execute(ddl);
        }

        // conn2
        try (Connection c2 = DriverManager.getConnection(url);
             PreparedStatement ps = c2.prepareStatement(insertSql)) {

            ps.setString(1, "x");
            ps.setString(2, "y");
            ps.executeUpdate();
        }

        // verify
        try (Connection c3 = DriverManager.getConnection(url);
             Statement st = c3.createStatement();
             ResultSet rs = st.executeQuery("SELECT COUNT(*) FROM parent_table")) {
            rs.next();
            assertEquals(1, rs.getInt(1));
        }
    }

    private void test4308_reproSingleConnectionPasses() throws Exception {
        String url = "jdbc:h2:mem:test_regression_single;DB_CLOSE_DELAY=-1";

        String ddl =
                "CREATE TABLE parent_table (" +
                        "  child_cd VARCHAR(31) NOT NULL CHECK (child_cd IN ('A','B')), " +
                        "  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "  name VARCHAR(255), " +
                        "  a_column VARCHAR(255), " +
                        "  b_column VARCHAR(255)" +
                        ")";


        String insertSql =
                "INSERT INTO parent_table (name, a_column, child_cd, id) " +
                        "VALUES (?, ?, 'A', DEFAULT)";

        try (Connection c = DriverManager.getConnection(url);
             Statement st = c.createStatement()) {
            st.execute(ddl);


            try (PreparedStatement ps = c.prepareStatement(
                    insertSql
            )) {
                ps.setString(1, "x");
                ps.setString(2, "y");
                ps.executeUpdate();
            }

            try (ResultSet rs = st.executeQuery("SELECT COUNT(*) FROM parent_table")) {
                rs.next();
                assertEquals(1, rs.getInt(1));
            }
        }
    }

    public static void main(String... args) throws Exception {
        TestBase.createCaller().init().testFromMain();
    }

}
