/*
 * Copyright 2004-2025 H2 Group. Multiple-Licensed under the MPL 2.0,
 * and the EPL 1.0 (https://h2database.com/html/license.html).
 * Initial Developer: H2 Group
 */
package org.h2.test.store.fuzz;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

import org.h2.test.TestBase;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;

/**
 * Seed-driven fuzz test for the MVStore.
 * <p>
 * Each run is generated by {@link FuzzGenerator} and saved to a trace file in
 * {@code src/test/resources/org/h2/test/store/fuzz/}. If the run passes the
 * file is deleted; if it fails the file is kept so it can be checked in and
 * replayed automatically by {@link #replayTests()}.
 */
public class TestMVStoreFuzz extends TestBase {

    private static final int GENERATE_RUNS = 100;
    private static final int OPS_PER_RUN = 10;

    /**
     * Run just this test.
     *
     * @param a ignored
     */
    public static void main(String... a) throws Exception {
        TestBase.createCaller().init().testFromMain();
    }

    @Override
    public void test() throws Exception {
        for (DynamicTest dt : (Iterable<DynamicTest>) generateFuzzTests()::iterator) {
            try {
                dt.getExecutable().execute();
            } catch (Exception | Error e) {
                throw e;
            } catch (Throwable t) {
                throw new RuntimeException(t);
            }
        }
        for (DynamicTest dt : (Iterable<DynamicTest>) replayTests()::iterator) {
            try {
                dt.getExecutable().execute();
            } catch (Exception | Error e) {
                throw e;
            } catch (Throwable t) {
                throw new RuntimeException(t);
            }
        }
    }

    @Disabled
    @TestFactory
    Stream<DynamicTest> generateFuzzTests() throws Exception {
        if (config == null) {
            init();
        }
        String fileName = "memFS:" + getTestName();
        SecureRandom seedRng = new SecureRandom();
        Stream<Long> seedStream = Stream.generate(seedRng::nextLong).limit(GENERATE_RUNS);
        return seedStream.map(seed -> DynamicTest.dynamicTest("seed=" + seed, () -> {
            Path traceFile = traceFilePath();
            new FuzzGenerator(seed).generate(OPS_PER_RUN).save(traceFile);
            try {
                runSeed(fileName, traceFile);
                Files.deleteIfExists(traceFile);
            } catch (FuzzScript.ReplayFailure ex) {
                FuzzScript truncated = FuzzScript.load(traceFile).truncateTo(ex.opIndex);
                truncated.save(traceFile);
                try {
                    runSeed(fileName, traceFile);
                    Files.deleteIfExists(traceFile);
                    println("intermittent failure seed=" + seed + " op=" + ex.opIndex
                            + " (not reproducible, file deleted)");
                } catch (FuzzScript.ReplayFailure confirmed) {
                    println("confirmed failure seed=" + seed + " op=" + ex.opIndex
                            + " trace=" + traceFile);
                }
                throw ex;
            }
        }));
    }

    /**
     * Replay all trace files checked in under
     * {@code src/test/resources/org/h2/test/store/fuzz/}.
     */
    @TestFactory
    Stream<DynamicTest> replayTests() throws Exception {
        if (config == null) {
            init();
        }
        String fileName = "memFS:" + getTestName() + "_replay";
        List<DynamicTest> tests = new ArrayList<>();
        Path dir = Paths.get("src", "test", "resources", "org", "h2", "test", "store", "fuzz");
        if (Files.isDirectory(dir)) {
            Files.list(dir)
                    .filter(p -> p.toString().endsWith(".txt"))
                    .sorted()
                    .forEach(p -> tests.add(DynamicTest.dynamicTest(
                            "replay:" + p.getFileName(),
                            () -> runSeed(fileName, p))));
        }
        return tests.stream();
    }

    /** Load {@code traceFile} and replay it. */
    private static void runSeed(String fileName, Path traceFile) throws FuzzScript.ReplayFailure, IOException {
        FuzzScript.load(traceFile).replay(fileName);
    }

    private static Path traceFilePath() throws IOException {
        Path dir = Paths.get("src", "test", "resources", "org", "h2", "test", "store", "fuzz");
        Files.createDirectories(dir);
        int next = 0;
        if (Files.isDirectory(dir)) {
            try (Stream<Path> ls = Files.list(dir)) {
                next = ls.map(p -> p.getFileName().toString())
                        .filter(n -> n.startsWith("fuzz-") && n.endsWith(".txt"))
                        .mapToInt(n -> {
                            try {
                                return Integer.parseInt(n.substring(5, n.length() - 4));
                            } catch (NumberFormatException e) {
                                return -1;
                            }
                        })
                        .max()
                        .orElse(-1) + 1;
            }
        }
        return dir.resolve("fuzz-" + next + ".txt");
    }
}
